// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package linksdb

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_url, short_name) VALUES ($1, $2, $3) RETURNING id, original_url, short_url, short_name, created_at
`

type CreateLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortUrl    string `json:"short_url"`
	ShortName   string `json:"short_name"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, original_url, short_url, short_name, created_at FROM links WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id int32) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByShortName = `-- name: GetLinkByShortName :one
SELECT id, original_url, short_url, short_name, created_at FROM links WHERE short_name = $1
`

func (q *Queries) GetLinkByShortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, original_url, short_url, short_name, created_at FROM links
`

func (q *Queries) ListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :execrows
UPDATE links SET original_url = $1, short_url = $2, short_name = $3 WHERE id = $4
`

type UpdateLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortUrl    string `json:"short_url"`
	ShortName   string `json:"short_name"`
	ID          int32  `json:"id"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLink,
		arg.OriginalUrl,
		arg.ShortUrl,
		arg.ShortName,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
