// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_visits.sql

package linksdb

import (
	"context"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT count(*) FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLinkVisitsByLinkID = `-- name: CountLinkVisitsByLinkID :one
SELECT count(*) FROM link_visits
WHERE link_id = $1
`

func (q *Queries) CountLinkVisitsByLinkID(ctx context.Context, linkID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkVisitsByLinkID, linkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (link_id, ip, user_agent, status)
VALUES ($1, $2, $3, $4)
RETURNING id, link_id, created_at, ip, user_agent, status
`

type CreateLinkVisitParams struct {
	LinkID    int32  `json:"link_id"`
	Ip        string `json:"ip"`
	UserAgent string `json:"user_agent"`
	Status    int32  `json:"status"`
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error) {
	row := q.db.QueryRow(ctx, createLinkVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Status,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Status,
	)
	return i, err
}

const listLinkVisits = `-- name: ListLinkVisits :many
SELECT id, link_id, created_at, ip, user_agent, status FROM link_visits
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListLinkVisitsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLinkVisits(ctx context.Context, arg ListLinkVisitsParams) ([]LinkVisit, error) {
	rows, err := q.db.Query(ctx, listLinkVisits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkVisitsByLinkID = `-- name: ListLinkVisitsByLinkID :many
SELECT id, link_id, created_at, ip, user_agent, status FROM link_visits
WHERE link_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListLinkVisitsByLinkIDParams struct {
	LinkID int32 `json:"link_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLinkVisitsByLinkID(ctx context.Context, arg ListLinkVisitsByLinkIDParams) ([]LinkVisit, error) {
	rows, err := q.db.Query(ctx, listLinkVisitsByLinkID, arg.LinkID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
