// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package linksdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          int32            `json:"id"`
	OriginalUrl string           `json:"original_url"`
	ShortUrl    string           `json:"short_url"`
	ShortName   string           `json:"short_name"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
