#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"
env_files = [".env"]

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  entrypoint = ["./tmp/main"]
  args_bin = []
  full_bin = ""
  delay = 300
  include_ext = ["go"]
  include_dir = []
  include_file = []
  exclude_dir = ["tmp", "bin", "vendor", "testdata", "scripts", ".git", "node_modules"]
  exclude_file = ["package.json", "package-lock.json", "go.sum"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  ignore_dangerous_root_dir = false
  log = "tmp/build-errors.log"
  poll = false
  poll_interval = 0
  pre_cmd = []
  post_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  kill_delay = "1s"
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  mode = ""
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  app_start_timeout = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
